# Calculate the area, volume and surface of the object generated by 2 different function

from scipy.integrate import quad
import numpy as np
import sympy as sm
import matplotlib.pyplot as plt

x = sm.Symbol('x', real = True) # SymPy counting

f = x**2
g = 2 * x 
# ---
f = sm.sympify(f)
g = sm.sympify(g)
c = sm.Abs(f - g)

# intersections: f(x) = g(x) or c(x) = 0
intersections = sm.solve(f - g, x)

# if we want special interval (R = float('-inf') , float('inf))
since = float('-inf')
to =  float('inf')

# intersections in the interval [since, to]
valid_intersections = []
for sol in intersections:
    val_eval = sol.evalf()
    # if the function is a polynom with complex solution
    if val_eval.is_real or abs(val_eval.as_real_imag()[1]) < 1e-7:
        val = float(val_eval.as_real_imag()[0])
        if since <= val <= to:
            valid_intersections.append(val)
        
# order ascent
valid_intersections.sort()
if len(valid_intersections) < 2:
    raise ValueError('There is 0 or 1 intersection')
    
a, b = valid_intersections[0], valid_intersections[1]

print(f'Intersections in interval: a = {a:.2f}, b = {b:.2f}')

# switch sm to np and plt (with special constant function)
if not f.free_symbols:
    f_num = lambda val: np.full_like(val, float(f.evalf()))
else:
    f_num = sm.lambdify(x, f, 'numpy')
    
if not g.free_symbols:
    g_num = lambda val: np.full_like(val, float(g.evalf()))
else:
    g_num = sm.lambdify(x, g, 'numpy')

c_num = sm.lambdify(x, c, 'numpy')

# ==============================================================

# area
area, _ = quad (c_num, a, b)

# volume
c_sq = c ** 2
c_sq_num = sm.lambdify(x, c_sq, 'numpy')
vol, _ = quad(c_sq_num, a, b)
volume = np.pi * vol

# surfaces
der = sm.diff(c, x)

ar_x = 2 * sm.pi * c * sm.sqrt(1 + der**2)
ar_x_num = sm.lambdify(x, ar_x, 'numpy')
surface_x, _ = quad(ar_x_num, a, b)

ar_y = 2 * sm.pi * x * sm.sqrt(1 + der**2)
ar_y_num = sm.lambdify(x, ar_y, 'numpy')
surface_y, _ = quad(ar_y_num, a, b)

# =====================================================

# plot the graph
x_graph = np.linspace(a-0.5, b+0.5, 1000)

f_graph = f_num(x_graph)
g_graph = g_num(x_graph)

plt.figure(figsize=(12, 7), layout='constrained')

# average on the interval [a, b]
x_mid = (a + b) / 2
if f_num(x_mid) > g_num(x_mid):
    label_f, label_g = 'Upper function', 'Lower function'
else:
    label_f, label_g = 'Lower function', 'Upper function'


# function and legend
plt.plot(x_graph, f_graph, color='crimson', linewidth=2.5, label=f'{label_f}: $f(x) = {f}$')
plt.plot(x_graph, g_graph, color='royalblue', linewidth=2.5, label=f'{label_g}: $g(x) = {g}$')

plt.plot([], [], color='crimson', linewidth=1.5, linestyle='--', alpha=0.7, label=f'Lower bound: $a$ = {a:.2f}')
plt.plot([], [], color='crimson', linewidth=1.5, linestyle='--', alpha=0.7, label=f'Upper bound: $b$ = {b:.2f}')

plt.plot([], [], ' ', label='----')

plt.plot([], [], ' ', label=f'Area: $S$ = {area:.2f}')
plt.plot([], [], ' ', label=f'Volume: $V$ = {volume:.2f}')
plt.plot([], [], ' ', label=f'Surface by $x$: $P_x$ = {surface_x:.2f}')
plt.plot([], [], ' ', label=f'Surface by $y$: $P_y$ = {surface_y:.2f}')

plt.axvline(a, color='crimson', linewidth=1.5, linestyle='--', alpha=0.7)
plt.axvline(b, color='crimson', linewidth=1.5, linestyle='--', alpha=0.7)

plt.axhline(f_num(a), color='crimson', linewidth=1.5, linestyle=':', alpha=0.7)
plt.axhline(f_num(b), color='crimson', linewidth=1.5, linestyle=':', alpha=0.7)

plt.axhline(0, color='gray', linewidth=1.5, linestyle='--', alpha=0.4)
plt.axvline(0, color='gray', linewidth=1.5, linestyle='--', alpha=0.4)

# area
x_fill = np.linspace(a, b, 500)
plt.fill_between(x_fill, f_num(x_fill), g_num(x_fill), color='purple', alpha=0.3)

plt.xlabel('X', fontsize=11)
plt.ylabel('Y', fontsize=11)

plt.title('Area and object between 2 functions', fontsize=13, weight='bold', pad=15)
plt.legend(fontsize=9, framealpha=0.9, loc='upper left', bbox_to_anchor=(1.02, 1))
plt.grid(True, linestyle=':', alpha=0.4)


plt.show()
